### ISSUE TITLE
Why is USB required/is it still required after copying file to init dir?

### ISSUE THREAD

**Issue by protopenguin** [bashalarmist/war-webos-ad-remover#1]
I wanted to figure out why we need the USB stick. I tried SSHing into the machine, downloading the script through wget and running it without the stick but I got no output and it didn't work (I tried to make sure it was executable).

I then inserted the USB drive in, copied the file via SSH to it and it ran ok from there. Is the USB drive really necessary? Why can't we just run it from the init folder?

Can I remove the drive after I copy the file to the init dir?

**Comment by ghost** [comment]
It's just a failsafe so if the TV doesn't boot you can unplug the USB and it will not run the adblocker script

If you change https://github.com/bashalarmist/war-webos-ad-remover/blob/main/webos_ad_remover#L13= to 

`WAR_USB_LOCATION='/tmp'` then it will work without a USB but you won't have anti-brick protection

**Comment by bashalarmist** [comment]
@BountyChocolate123456 is correct. This is a failsafe in case something goes wrong, either via an update or because of user modifications to the script with unintended consequences. In the next version of the script I will likely include an install option, but the user would have to accept that it is a riskier option. I am running an updated version of the script on my LG with persistence, and I have been doing so for about a month now.  I will get an update out soon.
